package view;

import java.awt.Window;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author N.Maliki
 */
public class Parentstudent extends javax.swing.JFrame {

    /**
     * Creates new form student
     */
    public Parentstudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        msg1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        StudentsTable = new javax.swing.JTable();
        printAllStudentsBtn = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        refreshStudentBtn = new javax.swing.JButton();
        backToDashBoardBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("STUDENTS");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        msg1.setBackground(new java.awt.Color(235, 252, 252));
        msg1.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        msg1.setForeground(new java.awt.Color(235, 252, 252));
        msg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msg1.setText("STUDENT");
        msg1.setAlignmentX(1.0F);
        msg1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel33.setBackground(new java.awt.Color(51, 0, 153));
        jLabel33.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(235, 252, 252));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("STUDENT");
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        StudentsTable.setBackground(new java.awt.Color(235, 252, 252));
        StudentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(StudentsTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                .addContainerGap())
        );

        printAllStudentsBtn.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        printAllStudentsBtn.setForeground(new java.awt.Color(0, 102, 102));
        printAllStudentsBtn.setText("Print");
        printAllStudentsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printAllStudentsBtnActionPerformed(evt);
            }
        });

        jPanel15.setBackground(new java.awt.Color(0, 102, 102));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        jPanel15.setForeground(new java.awt.Color(0, 102, 102));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setBackground(new java.awt.Color(51, 0, 153));
        jLabel31.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(235, 252, 252));
        jLabel31.setText("Enter the ID of the student");
        jPanel15.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 2, 300, 40));

        searchTextField.setBackground(new java.awt.Color(235, 252, 252));
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });
        jPanel15.add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 230, 40));

        SearchBtn.setFont(new java.awt.Font("Unispace", 0, 18)); // NOI18N
        SearchBtn.setForeground(new java.awt.Color(0, 102, 102));
        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        jPanel15.add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 50, 200, 40));

        refreshStudentBtn.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        refreshStudentBtn.setForeground(new java.awt.Color(0, 102, 102));
        refreshStudentBtn.setText("Refresh");
        refreshStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshStudentBtnActionPerformed(evt);
            }
        });

        backToDashBoardBtn.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        backToDashBoardBtn.setForeground(new java.awt.Color(0, 102, 102));
        backToDashBoardBtn.setText("Back");
        backToDashBoardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToDashBoardBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(msg1, javax.swing.GroupLayout.PREFERRED_SIZE, 968, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backToDashBoardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(refreshStudentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(printAllStudentsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(msg1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backToDashBoardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshStudentBtn)
                    .addComponent(printAllStudentsBtn))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void printAllStudentsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printAllStudentsBtnActionPerformed
        MessageFormat header = new MessageFormat("DISPLINE MANAGEMENT SYSTEM");
        MessageFormat footer = new MessageFormat("©25753__Maliki Ntwali");
        try {
            StudentsTable.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_printAllStudentsBtnActionPerformed

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // Retrieve the student name entered in searchTextField
        String studentName = searchTextField.getText();

        // JDBC connection parameters
        String url = "jdbc:postgresql://localhost:5432/displine_management_system_db";
        String user = "postgres";
        String password = "123";

        // SQL SELECT statement to retrieve student details by name
        String selectSql = "SELECT s.student_id, s.first_name, s.last_name, s.guardians_number, s.discipline_marks, s.date_of_birth, "
                + "COALESCE(SUM(p.marks_deducted), 0) AS total_marks_deducted "
                + "FROM students s LEFT JOIN punishment p ON s.student_id = s.student_id "
                + "WHERE s.first_name ILIKE ? OR s.last_name ILIKE ? "
                + "GROUP BY s.student_id";

        try (Connection conn = DriverManager.getConnection(url, user, password);
                PreparedStatement statement = conn.prepareStatement(selectSql)) {
            // Set the student name parameters for the prepared statement
            String namePattern = "%" + studentName + "%";
            statement.setString(1, namePattern);
            statement.setString(2, namePattern);

            // Execute the SELECT query
            ResultSet resultSet = statement.executeQuery();

            // Create a table model to hold the query results
            DefaultTableModel tableModel = new DefaultTableModel(
                    new String[]{"Student ID", "First Name", "Last Name", "Guardian's Number", "Discipline Marks", "Date of Birth", "Total Marks Deducted"},
                    0
            );

            // Check if any students with the entered name exist and populate the table model
            while (resultSet.next()) {
                int studentId = resultSet.getInt("student_id");
                String firstName = resultSet.getString("first_name");
                String lastName = resultSet.getString("last_name");
                String guardiansNumber = resultSet.getString("guardians_number");
                int disciplineMarks = resultSet.getInt("discipline_marks");
                String dateOfBirth = resultSet.getString("date_of_birth");
                int totalMarksDeducted = resultSet.getInt("total_marks_deducted");

                tableModel.addRow(new Object[]{studentId, firstName, lastName, guardiansNumber, disciplineMarks, dateOfBirth, totalMarksDeducted});
            }

            // Set the table model to the StudentsTable
            StudentsTable.setModel(tableModel);

            // If no student with the entered name is found, display a message
            if (tableModel.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No students found!", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void refreshStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshStudentBtnActionPerformed
        // JDBC connection parameters
        String url = "jdbc:postgresql://localhost:5432/displine_management_system_db";
        String user = "postgres";
        String password = "123";

        // SQL SELECT statement to retrieve all student data
        String selectSql = "SELECT * FROM students";

        try (Connection conn = DriverManager.getConnection(url, user, password);
                Statement statement = conn.createStatement()) {
            // Execute the SELECT query
            ResultSet resultSet = statement.executeQuery(selectSql);

            // Create a new DefaultTableModel to hold the data
            DefaultTableModel model = new DefaultTableModel();

            // Add columns to the model
            model.addColumn("Student ID");
            model.addColumn("First Name");
            model.addColumn("Last Name");
            model.addColumn("Guardian's Number");
            model.addColumn("Discipline Marks");
            model.addColumn("Date of Birth");
            model.addColumn("Class Name");

            // Populate the model with data from the ResultSet
            while (resultSet.next()) {
                Object[] rowData = {
                    resultSet.getInt("student_id"),
                    resultSet.getString("first_name"),
                    resultSet.getString("last_name"),
                    resultSet.getString("guardians_number"),
                    resultSet.getInt("discipline_marks"),
                    resultSet.getString("date_of_birth"),
                    resultSet.getString("class_name")
                };
                model.addRow(rowData);
            }

            // Set the model to the jTable
            StudentsTable.setModel(model);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_refreshStudentBtnActionPerformed

    private void backToDashBoardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToDashBoardBtnActionPerformed
        ParentDashboard f = new ParentDashboard();
        f.show();
        this.dispose();
    }//GEN-LAST:event_backToDashBoardBtnActionPerformed
// Method to clear text fieldss

    // Define a method to fetch class names from the database and populate the classCombo
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parentstudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTable StudentsTable;
    private javax.swing.JButton backToDashBoardBtn;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel msg1;
    private javax.swing.JButton printAllStudentsBtn;
    private javax.swing.JButton refreshStudentBtn;
    private javax.swing.JTextField searchTextField;
    // End of variables declaration//GEN-END:variables
}
