package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author N.Maliki
 */
public class Teacherpunishment extends javax.swing.JFrame {

    /**
     * Creates new form punishment
     */
    public Teacherpunishment() {
        initComponents();
        populateClassCombo();
        punishExecuteBtn.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        permittedStudentsTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        msg1 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        punishNameBox = new javax.swing.JTextField();
        PunishSearchBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        nameBox = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        punishExecuteBtn = new javax.swing.JButton();
        punishedPrintBtn = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        punishDaysBox = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        punishmentReasonBox = new javax.swing.JTextField();
        marksDeductedBox = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        classCombo = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        punishmentStudentsTable = new javax.swing.JTable();
        refreshBtn = new javax.swing.JButton();
        backToDashboardBtn = new javax.swing.JButton();

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel32.setBackground(new java.awt.Color(51, 0, 153));
        jLabel32.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(235, 252, 252));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel32.setText("PERMITTED STUDENTS");
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        permittedStudentsTable.setBackground(new java.awt.Color(235, 252, 252));
        permittedStudentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(permittedStudentsTable);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PUNISHMENT");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        msg1.setBackground(new java.awt.Color(235, 252, 252));
        msg1.setFont(new java.awt.Font("Unispace", 1, 36)); // NOI18N
        msg1.setForeground(new java.awt.Color(235, 252, 252));
        msg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        msg1.setText("PUNISHMENT");
        msg1.setAlignmentX(1.0F);
        msg1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel15.setBackground(new java.awt.Color(0, 102, 102));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        jPanel15.setForeground(new java.awt.Color(0, 102, 102));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setBackground(new java.awt.Color(51, 0, 153));
        jLabel31.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(235, 252, 252));
        jLabel31.setText("Enter the Names of the student to Give a punishment");
        jPanel15.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, 46));

        punishNameBox.setBackground(new java.awt.Color(235, 252, 252));
        punishNameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punishNameBoxActionPerformed(evt);
            }
        });
        jPanel15.add(punishNameBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 79, 260, 47));

        PunishSearchBtn.setFont(new java.awt.Font("Unispace", 0, 24)); // NOI18N
        PunishSearchBtn.setForeground(new java.awt.Color(0, 102, 102));
        PunishSearchBtn.setText("Search");
        PunishSearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PunishSearchBtnActionPerformed(evt);
            }
        });
        jPanel15.add(PunishSearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 200, 50));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel27.setBackground(new java.awt.Color(51, 0, 153));
        jLabel27.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(235, 252, 252));
        jLabel27.setText("Student Names");

        nameBox.setBackground(new java.awt.Color(235, 252, 252));
        nameBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameBoxActionPerformed(evt);
            }
        });

        jLabel29.setBackground(new java.awt.Color(51, 0, 153));
        jLabel29.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(235, 252, 252));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("ENTER DETAILS FOR PUNISHMENT FOR STUDENT");
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel28.setBackground(new java.awt.Color(51, 0, 153));
        jLabel28.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(235, 252, 252));
        jLabel28.setText("Class");

        punishExecuteBtn.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        punishExecuteBtn.setForeground(new java.awt.Color(0, 102, 102));
        punishExecuteBtn.setText("Execute");
        punishExecuteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punishExecuteBtnActionPerformed(evt);
            }
        });

        punishedPrintBtn.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        punishedPrintBtn.setForeground(new java.awt.Color(0, 102, 102));
        punishedPrintBtn.setText("Print Punishments");
        punishedPrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punishedPrintBtnActionPerformed(evt);
            }
        });

        jLabel30.setBackground(new java.awt.Color(51, 0, 153));
        jLabel30.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(235, 252, 252));
        jLabel30.setText("Punishment");

        punishDaysBox.setBackground(new java.awt.Color(235, 252, 252));
        punishDaysBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punishDaysBoxActionPerformed(evt);
            }
        });

        jLabel34.setBackground(new java.awt.Color(51, 0, 153));
        jLabel34.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(235, 252, 252));
        jLabel34.setText("Reason for Punishment");

        punishmentReasonBox.setBackground(new java.awt.Color(235, 252, 252));
        punishmentReasonBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                punishmentReasonBoxActionPerformed(evt);
            }
        });

        marksDeductedBox.setBackground(new java.awt.Color(235, 252, 252));
        marksDeductedBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marksDeductedBoxActionPerformed(evt);
            }
        });

        jLabel35.setBackground(new java.awt.Color(51, 0, 153));
        jLabel35.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(235, 252, 252));
        jLabel35.setText("Marks Deducted");

        classCombo.setBackground(new java.awt.Color(235, 252, 252));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(punishDaysBox, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(marksDeductedBox, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(punishExecuteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(punishedPrintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34)
                                    .addComponent(punishmentReasonBox, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(classCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(punishmentReasonBox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(punishDaysBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(marksDeductedBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(punishExecuteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(punishedPrintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLabel33.setBackground(new java.awt.Color(51, 0, 153));
        jLabel33.setFont(new java.awt.Font("Unispace", 1, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(235, 252, 252));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("PURNISHED STUDENTS");
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        punishmentStudentsTable.setBackground(new java.awt.Color(235, 252, 252));
        punishmentStudentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(punishmentStudentsTable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 504, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addContainerGap())
        );

        refreshBtn.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        refreshBtn.setForeground(new java.awt.Color(0, 102, 102));
        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });

        backToDashboardBtn.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        backToDashboardBtn.setForeground(new java.awt.Color(0, 102, 102));
        backToDashboardBtn.setText("Back");
        backToDashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToDashboardBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(msg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backToDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(msg1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backToDashboardBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refreshBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void punishNameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punishNameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_punishNameBoxActionPerformed

    private void PunishSearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PunishSearchBtnActionPerformed
        // Retrieve search criteria from GUI components (e.g., student ID or name)
        String searchCriteria = punishNameBox.getText();

        // JDBC connection parameters
        String url = "jdbc:postgresql://localhost:5432/displine_management_system_db";
        String user = "postgres";
        String password = "123";

        // SQL SELECT query
        String sql = "SELECT * FROM students WHERE first_name LIKE ? OR last_name LIKE ?";

        try (Connection conn = DriverManager.getConnection(url, user, password);
                PreparedStatement pstmt = conn.prepareStatement(sql)) {
            // Set parameters for the prepared statement
            pstmt.setString(1, "%" + searchCriteria + "%");
            pstmt.setString(2, "%" + searchCriteria + "%");

            // Execute the SQL query
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                // Student found, populate text boxes with student information
                nameBox.setText(rs.getString("first_name"));
                nameBox.setText(rs.getString("last_name"));
                punishExecuteBtn.setVisible(true);
                //
            } else {
                // Student not found, display message to user
                JOptionPane.showMessageDialog(this, "Student not found.", "Search Result", JOptionPane.INFORMATION_MESSAGE);
                punishExecuteBtn.setVisible(false);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            //clearTextFields();
        }
    }//GEN-LAST:event_PunishSearchBtnActionPerformed

    private void nameBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameBoxActionPerformed

    private void punishExecuteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punishExecuteBtnActionPerformed
        String studentNames = nameBox.getText();
        String reason = punishmentReasonBox.getText();
        String className = (String) classCombo.getSelectedItem();
        String punishment = punishDaysBox.getText();
        int marksDeducted = Integer.parseInt(marksDeductedBox.getText());

        // JDBC connection parameters
        String url = "jdbc:postgresql://localhost:5432/displine_management_system_db";
        String user = "postgres";
        String password = "123";

        // SQL INSERT statement to insert data into the "punishment" table
        String insertSql = "INSERT INTO punishment (student_names, reason, class_name, punishment, marks_deducted) VALUES (?, ?, ?, ?, ?)";

        try (Connection conn = DriverManager.getConnection(url, user, password);
                PreparedStatement statement = conn.prepareStatement(insertSql)) {
            // Set parameters for the prepared statement
            statement.setString(1, studentNames);
            statement.setString(2, reason);
            statement.setString(3, className);
            statement.setString(4, punishment);
            statement.setInt(5, marksDeducted);

            // Execute the INSERT query
            int rowsAffected = statement.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Punishment Recorded successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                clearTextFields();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to Record Punishment ", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_punishExecuteBtnActionPerformed

    private void punishDaysBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punishDaysBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_punishDaysBoxActionPerformed

    private void punishmentReasonBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punishmentReasonBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_punishmentReasonBoxActionPerformed

    private void marksDeductedBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marksDeductedBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marksDeductedBoxActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // JDBC connection parameters
        String url = "jdbc:postgresql://localhost:5432/displine_management_system_db";
        String user = "postgres";
        String password = "123";

        // SQL SELECT query to retrieve data from the "punishment" table
        String selectSql = "SELECT * FROM punishment";

        try (Connection conn = DriverManager.getConnection(url, user, password);
                Statement statement = conn.createStatement()) {
            // Execute the SQL query
            ResultSet resultSet = statement.executeQuery(selectSql);

            // Create a new DefaultTableModel to hold the data
            DefaultTableModel model = new DefaultTableModel();

            // Add columns to the model
            model.addColumn("Punishment ID");
            model.addColumn("Student Names");
            model.addColumn("Reason");
            model.addColumn("Class Name");
            model.addColumn("Punishment");
            model.addColumn("Marks Deducted");

            // Populate the model with data from the ResultSet
            while (resultSet.next()) {
                Object[] rowData = {
                    resultSet.getInt("punishment_id"),
                    resultSet.getString("student_names"),
                    resultSet.getString("reason"),
                    resultSet.getString("class_name"),
                    resultSet.getString("punishment"),
                    resultSet.getInt("marks_deducted")
                };
                model.addRow(rowData);
            }

            // Set the model to the jTable
            punishmentStudentsTable.setModel(model);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void backToDashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToDashboardBtnActionPerformed
        TeacherDashboard f = new TeacherDashboard();
        f.show();
        this.dispose();
    }//GEN-LAST:event_backToDashboardBtnActionPerformed

    private void punishedPrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_punishedPrintBtnActionPerformed
        // Set the title of the table
        String tableTitle = "Punished Students";
        // Create the header MessageFormat including the title
        MessageFormat header = new MessageFormat("DISPLINE MANAGEMENT SYSTEM - " + tableTitle);
        MessageFormat footer = new MessageFormat("©25753__Maliki Ntwali");
        try {
            punishmentStudentsTable.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_punishedPrintBtnActionPerformed
    private void populateClassCombo() {
        // JDBC connection parameters
        String url = "jdbc:postgresql://localhost:5432/displine_management_system_db";
        String user = "postgres";
        String password = "123";

        // SQL SELECT statement to retrieve class names
        String selectSql = "SELECT class_name FROM class";

        try (Connection conn = DriverManager.getConnection(url, user, password);
                Statement statement = conn.createStatement();
                ResultSet resultSet = statement.executeQuery(selectSql)) {
            // Clear existing items in the combo box
            classCombo.removeAllItems();

            // Populate the combo box with class names
            while (resultSet.next()) {
                classCombo.addItem(resultSet.getString("class_name"));
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void clearTextFields() {
        punishNameBox.setText("");
        nameBox.setText("");
        punishmentReasonBox.setText("");
        punishDaysBox.setText("");
        marksDeductedBox.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(punishment.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(punishment.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(punishment.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(punishment.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new punishment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PunishSearchBtn;
    private javax.swing.JButton backToDashboardBtn;
    private javax.swing.JComboBox<String> classCombo;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField marksDeductedBox;
    private javax.swing.JLabel msg1;
    private javax.swing.JTextField nameBox;
    private javax.swing.JTable permittedStudentsTable;
    private javax.swing.JTextField punishDaysBox;
    private javax.swing.JButton punishExecuteBtn;
    private javax.swing.JTextField punishNameBox;
    private javax.swing.JButton punishedPrintBtn;
    private javax.swing.JTextField punishmentReasonBox;
    private javax.swing.JTable punishmentStudentsTable;
    private javax.swing.JButton refreshBtn;
    // End of variables declaration//GEN-END:variables
}
